### ISSUE TITLE
Week 6 Ready for Review

### ISSUE THREAD

**Issue by jhaefner97** [jhaefner97/FishingGuide#4]
Hi @pawaitemadisoncollege week 6 is ready for review, I opted to have my indie project setup in AWS. 

The site can be found here - http://castandclimate-env.eba-9mgat7ms.us-east-2.elasticbeanstalk.com/

**Comment by pawaitemadisoncollege** [comment]
Also be sure to add your indie project aws url to the list of indie projects in the student repo. Thanks!

**Comment by jhaefner97** [comment]
Hi @pawaitemadisoncollege I have the project connected to a database, but it is just my user table that I am using to store some things. This is not "visible". Is this an issue or is this okay for now? I do have API data being presented.

**Comment by jhaefner97** [comment]
Nevermind...hit a groove. This is visible now in the profile section, and the functionality is used when the user visits the fishing guide page and a basic "profile" can be viewed.

**Comment by pawaitemadisoncollege** [comment]
Hi @jhaefner97 I just verified I'm able to log in and see my profile data. Good work!
